"""Initial core tables

Revision ID: 98cd5d4fe8da
Revises: 
Create Date: 2026-07-24 15:10:15.287102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '98cd5d4fe8da'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # DB-002: ensure pgvector is available for later knowledge_chunks embeddings.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('artist', sa.String(length=512), nullable=False),
    sa.Column('album', sa.String(length=512), nullable=True),
    sa.Column('isrc', sa.String(length=32), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isrc')
    )
    op.create_index('ix_tracks_artist_title', 'tracks', ['artist', 'title'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('locale', sa.String(length=16), nullable=False),
    sa.Column('account_state', sa.String(length=32), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('guest_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('migrated_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['migrated_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_guest_sessions_expires_at', 'guest_sessions', ['expires_at'], unique=False)
    op.create_table('track_provider_ids',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('track_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_track_id', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_track_id', name='uq_track_provider_identity')
    )
    op.create_index('ix_track_provider_ids_provider', 'track_provider_ids', ['provider'], unique=False)
    op.create_index('ix_track_provider_ids_track_id', 'track_provider_ids', ['track_id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('discovery_mode', sa.String(length=32), nullable=False),
    sa.Column('profile', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'version', name='uq_user_preferences_user_version')
    )
    op.create_index('ix_user_preferences_user_id', 'user_preferences', ['user_id'], unique=False)
    op.create_table('recommendation_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('guest_session_id', sa.Uuid(), nullable=True),
    sa.Column('intent', sa.String(length=64), nullable=False),
    sa.Column('request_context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('engine_used', sa.String(length=64), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fallback_used', sa.Boolean(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['guest_session_id'], ['guest_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recommendation_sessions_request_id', 'recommendation_sessions', ['request_id'], unique=False)
    op.create_index('ix_recommendation_sessions_status', 'recommendation_sessions', ['status'], unique=False)
    op.create_index('ix_recommendation_sessions_user_id', 'recommendation_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_recommendation_sessions_user_id', table_name='recommendation_sessions')
    op.drop_index('ix_recommendation_sessions_status', table_name='recommendation_sessions')
    op.drop_index('ix_recommendation_sessions_request_id', table_name='recommendation_sessions')
    op.drop_table('recommendation_sessions')
    op.drop_index('ix_user_preferences_user_id', table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_index('ix_track_provider_ids_track_id', table_name='track_provider_ids')
    op.drop_index('ix_track_provider_ids_provider', table_name='track_provider_ids')
    op.drop_table('track_provider_ids')
    op.drop_index('ix_guest_sessions_expires_at', table_name='guest_sessions')
    op.drop_table('guest_sessions')
    op.drop_table('users')
    op.drop_index('ix_tracks_artist_title', table_name='tracks')
    op.drop_table('tracks')
    # ### end Alembic commands ###
