"""Add gen_random_uuid() server defaults to every UUID primary key

Primary keys are declared in ``contracts/db_models.py`` with a Python-side
``default=uuid.uuid4`` and no server default, so only SQLAlchemy could insert a
row. Any other writer — the n8n Postgres nodes, psql, a future service — hit:

    null value in column "id" of relation "guest_sessions"
    violates not-null constraint

This surfaced when WF-001's `Resolve User or Guest` and `Record Request Metrics`
nodes ran against the live database for the first time (Phase 2 §2.6 wiring).

`gen_random_uuid()` is built into PostgreSQL 13+ (the stack runs pg16), so no
extension is required. Adding a server default is additive and does not change
SQLAlchemy's behaviour: it keeps sending its own ``uuid4`` value, which takes
precedence over the default.

Revision ID: a7b3c9d1e5f2
Revises: f1a2b3c4d5e6
Create Date: 2026-07-25 10:30:00.000000

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a7b3c9d1e5f2"
down_revision: Union[str, Sequence[str], None] = "f1a2b3c4d5e6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Every table whose primary key is a UUID generated by the application.
_TABLES: tuple[str, ...] = (
    "users",
    "guest_sessions",
    "user_preferences",
    "feedback_events",
    "recommendation_sessions",
    "recommendation_candidates",
    "tracks",
    "track_provider_ids",
    "track_audio_features",
    "genre_nodes",
    "genre_edges",
    "knowledge_documents",
    "knowledge_chunks",
    "playlist_exports",
    "audio_jobs",
    "model_usage",
    "jobs",
    "audit_events",
)


def upgrade() -> None:
    """Let PostgreSQL generate the primary key when the writer does not."""
    for table in _TABLES:
        op.execute(
            f'ALTER TABLE "{table}" ALTER COLUMN id SET DEFAULT gen_random_uuid()'
        )


def downgrade() -> None:
    """Return primary keys to application-only generation."""
    for table in _TABLES:
        op.execute(f'ALTER TABLE "{table}" ALTER COLUMN id DROP DEFAULT')
