"""Add remaining tables and indexes

Revision ID: dc82e50ee3c9
Revises: 98cd5d4fe8da
Create Date: 2026-07-24 15:18:36.144279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dc82e50ee3c9'
down_revision: Union[str, Sequence[str], None] = '98cd5d4fe8da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genre_nodes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['genre_nodes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_genre_nodes_name', 'genre_nodes', ['name'], unique=False)
    op.create_index('ix_genre_nodes_parent_id', 'genre_nodes', ['parent_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_type', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_jobs_job_type', 'jobs', ['job_type'], unique=False)
    op.create_index('ix_jobs_state', 'jobs', ['state'], unique=False)
    op.create_table('knowledge_documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=True),
    sa.Column('uri', sa.String(length=2048), nullable=True),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'uri', 'version', name='uq_knowledge_document_version')
    )
    op.create_index('ix_knowledge_documents_source', 'knowledge_documents', ['source'], unique=False)
    op.create_table('model_usage',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('cache_hit', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_model_usage_provider_model', 'model_usage', ['provider', 'model'], unique=False)
    op.create_index('ix_model_usage_request_id', 'model_usage', ['request_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('resource', sa.String(length=255), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_events_action', 'audit_events', ['action'], unique=False)
    op.create_index('ix_audit_events_actor_user_id', 'audit_events', ['actor_user_id'], unique=False)
    op.create_index('ix_audit_events_created_at', 'audit_events', ['created_at'], unique=False)
    op.create_table('genre_edges',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('relation', sa.String(length=32), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['genre_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['genre_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'target_id', 'relation', name='uq_genre_edge_identity')
    )
    op.create_index('ix_genre_edges_relation', 'genre_edges', ['relation'], unique=False)
    op.create_index('ix_genre_edges_source_id', 'genre_edges', ['source_id'], unique=False)
    op.create_index('ix_genre_edges_target_id', 'genre_edges', ['target_id'], unique=False)
    op.create_table('knowledge_chunks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('content_tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', chunk_text)", persisted=True), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('ingestion_version', sa.String(length=64), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_knowledge_chunks_content_tsv', 'knowledge_chunks', ['content_tsv'], unique=False, postgresql_using='gin')
    op.create_index('ix_knowledge_chunks_document_id', 'knowledge_chunks', ['document_id'], unique=False)
    op.create_index('ix_knowledge_chunks_embedding_hnsw', 'knowledge_chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_table('playlist_exports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_playlist_id', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('partial_failure', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_playlist_exports_idempotency_key')
    )
    op.create_index('ix_playlist_exports_provider', 'playlist_exports', ['provider'], unique=False)
    op.create_index('ix_playlist_exports_user_id', 'playlist_exports', ['user_id'], unique=False)
    op.create_table('track_audio_features',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('track_id', sa.Uuid(), nullable=False),
    sa.Column('bpm', sa.Float(), nullable=True),
    sa.Column('musical_key', sa.String(length=16), nullable=True),
    sa.Column('camelot', sa.String(length=8), nullable=True),
    sa.Column('energy', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('track_id', 'source', 'model_version', name='uq_track_audio_features_version')
    )
    op.create_index('ix_track_audio_features_track_id', 'track_audio_features', ['track_id'], unique=False)
    op.create_table('audio_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('guest_session_id', sa.Uuid(), nullable=True),
    sa.Column('object_reference', sa.String(length=1024), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('derived_features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cleanup_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['guest_session_id'], ['guest_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audio_jobs_cleanup_at', 'audio_jobs', ['cleanup_at'], unique=False)
    op.create_index('ix_audio_jobs_state', 'audio_jobs', ['state'], unique=False)
    op.create_index('ix_audio_jobs_user_id', 'audio_jobs', ['user_id'], unique=False)
    op.create_table('recommendation_candidates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recommendation_session_id', sa.Uuid(), nullable=False),
    sa.Column('track_id', sa.Uuid(), nullable=True),
    sa.Column('feature_values', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('component_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('final_rank', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_session_id'], ['recommendation_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recommendation_candidates_session_id', 'recommendation_candidates', ['recommendation_session_id'], unique=False)
    op.create_index('ix_recommendation_candidates_session_rank', 'recommendation_candidates', ['recommendation_session_id', 'final_rank'], unique=False)
    op.create_index('ix_recommendation_candidates_track_id', 'recommendation_candidates', ['track_id'], unique=False)
    op.create_table('feedback_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recommendation_session_id', sa.Uuid(), nullable=True),
    sa.Column('candidate_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('guest_session_id', sa.Uuid(), nullable=True),
    sa.Column('track_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['recommendation_candidates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['guest_session_id'], ['guest_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recommendation_session_id'], ['recommendation_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_feedback_events_candidate_id', 'feedback_events', ['candidate_id'], unique=False)
    op.create_index('ix_feedback_events_event_type', 'feedback_events', ['event_type'], unique=False)
    op.create_index('ix_feedback_events_session_id', 'feedback_events', ['recommendation_session_id'], unique=False)
    op.create_index('ix_feedback_events_user_id', 'feedback_events', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_feedback_events_user_id', table_name='feedback_events')
    op.drop_index('ix_feedback_events_session_id', table_name='feedback_events')
    op.drop_index('ix_feedback_events_event_type', table_name='feedback_events')
    op.drop_index('ix_feedback_events_candidate_id', table_name='feedback_events')
    op.drop_table('feedback_events')
    op.drop_index('ix_recommendation_candidates_track_id', table_name='recommendation_candidates')
    op.drop_index('ix_recommendation_candidates_session_rank', table_name='recommendation_candidates')
    op.drop_index('ix_recommendation_candidates_session_id', table_name='recommendation_candidates')
    op.drop_table('recommendation_candidates')
    op.drop_index('ix_audio_jobs_user_id', table_name='audio_jobs')
    op.drop_index('ix_audio_jobs_state', table_name='audio_jobs')
    op.drop_index('ix_audio_jobs_cleanup_at', table_name='audio_jobs')
    op.drop_table('audio_jobs')
    op.drop_index('ix_track_audio_features_track_id', table_name='track_audio_features')
    op.drop_table('track_audio_features')
    op.drop_index('ix_playlist_exports_user_id', table_name='playlist_exports')
    op.drop_index('ix_playlist_exports_provider', table_name='playlist_exports')
    op.drop_table('playlist_exports')
    op.drop_index('ix_knowledge_chunks_embedding_hnsw', table_name='knowledge_chunks', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index('ix_knowledge_chunks_document_id', table_name='knowledge_chunks')
    op.drop_index('ix_knowledge_chunks_content_tsv', table_name='knowledge_chunks', postgresql_using='gin')
    op.drop_table('knowledge_chunks')
    op.drop_index('ix_genre_edges_target_id', table_name='genre_edges')
    op.drop_index('ix_genre_edges_source_id', table_name='genre_edges')
    op.drop_index('ix_genre_edges_relation', table_name='genre_edges')
    op.drop_table('genre_edges')
    op.drop_index('ix_audit_events_created_at', table_name='audit_events')
    op.drop_index('ix_audit_events_actor_user_id', table_name='audit_events')
    op.drop_index('ix_audit_events_action', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index('ix_model_usage_request_id', table_name='model_usage')
    op.drop_index('ix_model_usage_provider_model', table_name='model_usage')
    op.drop_table('model_usage')
    op.drop_index('ix_knowledge_documents_source', table_name='knowledge_documents')
    op.drop_table('knowledge_documents')
    op.drop_index('ix_jobs_state', table_name='jobs')
    op.drop_index('ix_jobs_job_type', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('ix_genre_nodes_parent_id', table_name='genre_nodes')
    op.drop_index('ix_genre_nodes_name', table_name='genre_nodes')
    op.drop_table('genre_nodes')
    # ### end Alembic commands ###
